spring:
  application:
    name: financial-entity-service
  profiles:
    default: dev

server:
  port: 8080

info:
  app:
    name: "${spring.application.name}"
    description: "Financial Entity Service"
    version: "1.0.0"