spring:
  config:
    import: optional:configserver:http://localhost:8070
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/dashboard-development/protocol/openid-connect/certs