name: API Gateway Server CD

on:
  push:
    branches: [ "main" ]
    paths: [ "api-gateway-server/**" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy API Gateway Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Login into docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build with Gradle Wrapper
        run: cd api-gateway-server && ./gradlew jib
